### ISSUE TITLE
New Action/Service Creation

### ISSUE THREAD

**Issue by Oberacda** [fzi-forschungszentrum-informatik/ros2_ros_bt_py#18]
In the BT Workshop, an idea was introduced to modify actions and services in a way that all goal/result fields are available as inputs/outputs and you can decide while building the BT which of those you want to set and which to set as an option. This requires a major overhaul of how nodes are actually generated but might be a good feature to reduce GetAttr/SetAttr patterns without custom node usage

**Comment by nspielbau** [comment]
Closed by #100
