### ISSUE TITLE
Documenation: How do I use this?

### ISSUE THREAD

**Issue by Oberacda** [fzi-forschungszentrum-informatik/ros2_ros_bt_py#4]
This package already contains documentation on how to build and start it and how to write own nodes, but it doesn't contain any instructions for newcomers.

* How do I create a new tree?
* Where do I start / What kind of options for a root node do I have?
* How do I use the web GUI? Where do I add inputs, etc

I think a tutorial on building an example tree and explaining all the steps along the way would be very handy.

**Comment by nspielbau** [comment]
Are we missing something here after #118 ?

**Comment by nspielbau** [comment]
@Oberacda
