### ISSUE TITLE
Data Wiring duplication check seems to not delete Date when moving/deleting Nodes

### ISSUE THREAD

**Issue by Oberacda** [fzi-forschungszentrum-informatik/ros2_ros_bt_py#41]
# Bug Report

### Description

When constructing a tree, adding the wiring works, then removing a node, adding it again and re-adding the wiring fails with the error:
```python
"Failed to wire data null to null: {
    "error_message": "Failed to execute wiring "source: \n node_name: "TopicSubscriber"\n data_kind: "outputs"\n data_key: "message"\ntarget: \n node_name: "MessageToFields"\n data_kind: "inputs"\n data_key: "in"": Duplicate subscription!",
     "success": false
}"
```
It seems that the check for duplicate subscriptions is not reset.
This Error persists even when Removing and Adding the Nodes in question again.

Removing the source node also resolved the issue.
The faulty connection persisted into a tree yaml on disk.

[06_topic_subscriber.yaml.txt](https://github.com/fzi-forschungszentrum-informatik/ros2_ros_bt_py/files/13706553/06_topic_subscriber.yaml.txt)

**Comment by mdeitersen** [comment]
working on it
